apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-app
  labels:
    app: bad-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bad-app
  template:
    metadata:
      labels:
        app: bad-app
    spec:
      containers:
      - name: bad-app
        image: dfreilich/goflake-server:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /fake
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessPobe:
          httpGet:
            path: /fake
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
