apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-app
  labels:
    app: good-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: good-app
  template:
    metadata:
      labels:
        app: good-app
    spec:
      containers:
      - name: good-app
        image: dfreilich/goflake-server:latest
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 1
          timeoutSeconds: 1
        livenessPobe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
